// Generated by npm run xdr:build from analyze.mjs; commit this standalone evaluator.
// No runtime imports, disk access, or build-time secret substitution.

// xdr/web-injection/patterns.json
var patterns_default = {
  technique: "T1190",
  thresholds: { block: 0.85, alert: 0.5 },
  minRepeats: 8,
  windowSeconds: 120,
  blockTtlSeconds: 900,
  patterns: [
    { name: "sql_injection", condition: "SQL \uAD6C\uBB38 \uACB0\uD569\xB7\uB17C\uB9AC\uC2DD\xB7UNION SELECT \uB4F1\uC758 \uAD6C\uCCB4 \uC2E0\uD638\uAC00 \uAC19\uC740 \uC8FC\uC18C\uC5D0\uC11C 120\uCD08 \uB0B4 8\uD68C \uC774\uC0C1; \uC9D1\uACC4 \uACBD\uBCF4 \uC218\uC90010 \uC774\uC0C1", evidence: "T1190 \uACF5\uAC1C \uC571 SQL \uC8FC\uC785 \uC545\uC6A9; SQL/select \uB2E8\uC5B4\uB9CC\uC73C\uB85C \uD574\uB2F9\uD558\uC9C0 \uC54A\uB294\uB2E4.", source: "https://attack.mitre.org/techniques/T1190/" },
    { name: "script_injection", condition: "\uC2E4\uC81C \uC2A4\uD06C\uB9BD\uD2B8 \uD0DC\uADF8/\uC774\uBCA4\uD2B8 \uD578\uB4E4\uB7EC \uB610\uB294 \uC0BD\uC785 \uD45C\uC2DD \uBC18\uBCF5 8\uD68C \uC774\uC0C1", evidence: "T1190 \uACF5\uAC1C \uC6F9 \uC571\uC758 \uC785\uB825 \uCC98\uB9AC \uCDE8\uC57D\uC810 \uC545\uC6A9; \uC218\uC5C5 script \uB2E8\uC5B4\uB294 \uADFC\uAC70 \uBD80\uC871.", source: "https://attack.mitre.org/techniques/T1190/" },
    { name: "path_traversal", condition: "../ \uC5F0\uC18D \uB610\uB294 \uACBD\uB85C \uC774\uD0C8 \uD45C\uAE30 \uBC18\uBCF5 8\uD68C \uC774\uC0C1", evidence: "T1190 \uACF5\uAC1C \uC571\uC758 \uACBD\uB85C \uCC98\uB9AC \uCDE8\uC57D\uC810 \uC545\uC6A9; up \uB2E8\uC5B4\uB294 \uACBD\uB85C \uC774\uD0C8\uC774 \uC544\uB2C8\uB2E4.", source: "https://attack.mitre.org/techniques/T1190/" },
    { name: "command_injection", condition: "\uBA85\uB839 \uAD6C\uBD84\uC790\uC640 \uC2E4\uD589 \uBA85\uB839 \uACB0\uD569 \uB610\uB294 \uBA85\uB839 \uAD6C\uBD84\uC790 \uC9D1\uACC4 \uACBD\uBCF4 \uBC18\uBCF5 8\uD68C \uC774\uC0C1", evidence: "T1190 \uACF5\uAC1C \uC571\uC5D0\uC11C \uC785\uB825\uC744 \uBA85\uB839\uC73C\uB85C \uD574\uC11D\uD558\uB294 \uCDE8\uC57D\uC810 \uC545\uC6A9.", source: "https://attack.mitre.org/techniques/T1190/" },
    { name: "ambiguous_web_input", condition: "\uB2E8\uC77C \uD45C\uC2DD/\uB530\uC634\uD45C/\uAE34 \uC785\uB825/\uC218\uC5C5 \uB2E8\uC5B4 \uB4F1 \uBA85\uD655\uD55C \uBC18\uBCF5 \uADFC\uAC70 \uBD80\uC871", evidence: "T1190 \uBC94\uC8FC\uB9CC\uC73C\uB85C \uACF5\uACA9\uC744 \uD655\uC815\uD560 \uC218 \uC5C6\uC5B4 Jev\uB85C \uC218\uCE58 \uADFC\uAC70\uB97C \uD3C9\uAC00\uD55C\uB2E4.", source: "https://attack.mitre.org/techniques/T1190/" }
  ]
};

// scripts/xdr-portable/net.mjs
function isIP(value) {
  if (typeof value !== "string") return 0;
  if (/^(?:0|[1-9]\d{0,2})(?:\.(?:0|[1-9]\d{0,2})){3}$/u.test(value)) {
    return value.split(".").every((part) => Number(part) <= 255) ? 4 : 0;
  }
  if (!value.includes(":") || /[^0-9a-f:.]/iu.test(value)) return 0;
  let address = value;
  if (address.includes(".")) {
    const index = address.lastIndexOf(":");
    if (isIP(address.slice(index + 1)) !== 4) return 0;
    address = address.slice(0, index + 1) + "0:0";
  }
  const halves = address.split("::");
  if (halves.length > 2) return 0;
  const groups = halves.flatMap((half) => half === "" ? [] : half.split(":"));
  if (!groups.every((group) => /^[0-9a-f]{1,4}$/iu.test(group))) return 0;
  return (halves.length === 2 ? groups.length < 8 : groups.length === 8) ? 6 : 0;
}

// node_modules/@noble/hashes/_u64.js
var fromNumH = (n) => n / 2 ** 32 | 0;
var fromNumL = (n) => n >>> 0;
function setU64FromNum(view, byteOffset, n, isLE) {
  const h = fromNumH(n);
  const l = fromNumL(n);
  view.setUint32(byteOffset, isLE ? l : h, isLE);
  view.setUint32(byteOffset + 4, isLE ? h : l, isLE);
}

// node_modules/@noble/hashes/utils.js
function isBytes(a) {
  return a instanceof Uint8Array || ArrayBuffer.isView(a) && a.constructor.name === "Uint8Array" && "BYTES_PER_ELEMENT" in a && a.BYTES_PER_ELEMENT === 1;
}
var atitle = (title) => title ? `"${title}" ` : "";
function anumber(n, title = "") {
  if (typeof n !== "number")
    throw new TypeError(atitle(title) + "expected number, got " + typeof n);
  if (!Number.isSafeInteger(n) || n < 0)
    throw new RangeError(atitle(title) + "expected integer >= 0, got " + n);
  return n;
}
function abytes(value, length, title = "") {
  if (isBytes(value) && (length === void 0 || value.length === length))
    return value;
  if (length !== void 0)
    anumber(length, "length");
  const bytes = isBytes(value);
  const ofLen = length !== void 0 ? ` of length ${length}` : "";
  const got = bytes ? `length=${value.length}` : `type=${typeof value}`;
  const message = atitle(title) + "expected Uint8Array" + ofLen + ", got " + got;
  if (!bytes)
    throw new TypeError(message);
  throw new RangeError(message);
}
var aobject = (value, label) => {
  if (value === null || typeof value !== "object" || Array.isArray(value))
    throw new TypeError((label === "object" ? "" : `"${label}" `) + "expected object, got type=" + typeof value);
};
var aopts = (value, label) => {
  aobject(value, label);
  const proto = Object.getPrototypeOf(value);
  if (proto !== Object.prototype && proto !== null)
    throw new TypeError(`"${label}" expected plain object`);
  if (Object.hasOwn(value, "__proto__"))
    throw new TypeError(`"${label}.__proto__" is not allowed`);
};
function aexists(instance, checkFinished = true) {
  if (instance.destroyed)
    throw new Error("hash was destroyed");
  if (checkFinished && instance.finished)
    throw new Error("digest() was already called");
}
function aoutput(out, instance) {
  abytes(out, void 0, "output");
  const min = instance.outputLen;
  if (!(out.length >= min)) {
    throw new RangeError('"output" expected length >= ' + min);
  }
}
function clean(...arrays) {
  for (let i = 0; i < arrays.length; i++) {
    arrays[i].fill(0);
  }
}
function createView(arr) {
  return new DataView(arr.buffer, arr.byteOffset, arr.byteLength);
}
function rotr(word, shift) {
  return word << 32 - shift | word >>> shift;
}
var hasHexBuiltin = /* @__PURE__ */ (() => (
  // @ts-ignore
  typeof Uint8Array.from([]).toHex === "function" && typeof Uint8Array.fromHex === "function"
))();
var hexes = /* @__PURE__ */ Array.from({ length: 256 }, (_, i) => i.toString(16).padStart(2, "0"));
function bytesToHex(bytes) {
  abytes(bytes);
  if (hasHexBuiltin)
    return bytes.toHex();
  let hex = "";
  for (let i = 0; i < bytes.length; i++) {
    hex += hexes[bytes[i]];
  }
  return hex;
}
function checkOpts(defaults, opts, title = "opts") {
  aopts(defaults, "defaults");
  if (opts !== void 0)
    aopts(opts, title);
  const merged = Object.assign(/* @__PURE__ */ Object.create(null), defaults, opts);
  return merged;
}
function createHasher(hashCons, info = {}) {
  if (typeof hashCons !== "function")
    throw new TypeError('"hashCons" expected function, got type=' + typeof hashCons);
  info = checkOpts({}, info, "info");
  const hashC = (msg, opts) => hashCons(opts).update(msg).digest();
  const tmp = hashCons(void 0);
  hashC.outputLen = tmp.outputLen;
  hashC.blockLen = tmp.blockLen;
  hashC.canXOF = tmp.canXOF;
  hashC.create = (opts) => hashCons(opts);
  Object.assign(hashC, info);
  return Object.freeze(hashC);
}
var oidNist = (suffix) => ({
  // Current NIST hashAlgs suffixes used here fit in one DER subidentifier octet.
  // Larger suffix values would need base-128 OID encoding and a different length byte.
  oid: Uint8Array.from([6, 9, 96, 134, 72, 1, 101, 3, 4, 2, suffix])
});

// node_modules/@noble/hashes/_md.js
function Chi(a, b, c) {
  return a & b ^ ~a & c;
}
function Maj(a, b, c) {
  return a & b ^ a & c ^ b & c;
}
var HashMD = class {
  blockLen;
  outputLen;
  canXOF = false;
  padOffset;
  isLE;
  // For partial updates less than block size
  buffer;
  view;
  finished = false;
  length = 0;
  pos = 0;
  destroyed = false;
  constructor(blockLen, outputLen, padOffset, isLE) {
    this.blockLen = blockLen;
    this.outputLen = outputLen;
    this.padOffset = padOffset;
    this.isLE = isLE;
    this.buffer = new Uint8Array(blockLen);
    this.view = createView(this.buffer);
  }
  update(data) {
    aexists(this);
    abytes(data);
    const { view, buffer, blockLen } = this;
    const len = data.length;
    let processed = false;
    for (let pos = 0; pos < len; ) {
      const take = Math.min(blockLen - this.pos, len - pos);
      if (take === blockLen) {
        const dataView = createView(data);
        for (; blockLen <= len - pos; pos += blockLen)
          this.process(dataView, pos);
        processed = true;
        continue;
      }
      buffer.set(pos === 0 && take === len ? data : data.subarray(pos, pos + take), this.pos);
      this.pos += take;
      pos += take;
      if (this.pos === blockLen) {
        this.process(view, 0);
        this.pos = 0;
        processed = true;
      }
    }
    this.length += data.length;
    if (processed)
      this.roundClean();
    return this;
  }
  digestInto(out) {
    aexists(this);
    aoutput(out, this);
    this.finished = true;
    const { buffer, view, blockLen, isLE } = this;
    let { pos } = this;
    buffer[pos++] = 128;
    buffer.fill(0, pos);
    if (this.padOffset > blockLen - pos) {
      this.process(view, 0);
      buffer.fill(0);
    }
    setU64FromNum(view, blockLen - 8, this.length * 8, isLE);
    this.process(view, 0);
    this.roundClean();
    const oview = out === buffer ? view : createView(out);
    const len = this.outputLen;
    const outLen = len / 4;
    const state = this.get();
    if (len % 4 || outLen > state.length)
      throw new Error("invalid outputLen");
    for (let i = 0; i < outLen; i++)
      oview.setUint32(4 * i, state[i], isLE);
  }
  digest() {
    const { buffer, outputLen } = this;
    this.digestInto(buffer);
    const res = buffer.slice(0, outputLen);
    this.destroy();
    return res;
  }
  _cloneIntoMeta(to) {
    const { buffer, length, finished, destroyed, pos } = this;
    to.destroyed = destroyed;
    to.finished = finished;
    to.length = length;
    to.pos = pos;
    if (pos)
      to.buffer.set(buffer);
    return to;
  }
  clone() {
    return this._cloneInto();
  }
};
var SHA256_IV = /* @__PURE__ */ Uint32Array.from([
  1779033703,
  3144134277,
  1013904242,
  2773480762,
  1359893119,
  2600822924,
  528734635,
  1541459225
]);

// node_modules/@noble/hashes/sha2.js
var SHA256_K = /* @__PURE__ */ Uint32Array.from([
  1116352408,
  1899447441,
  3049323471,
  3921009573,
  961987163,
  1508970993,
  2453635748,
  2870763221,
  3624381080,
  310598401,
  607225278,
  1426881987,
  1925078388,
  2162078206,
  2614888103,
  3248222580,
  3835390401,
  4022224774,
  264347078,
  604807628,
  770255983,
  1249150122,
  1555081692,
  1996064986,
  2554220882,
  2821834349,
  2952996808,
  3210313671,
  3336571891,
  3584528711,
  113926993,
  338241895,
  666307205,
  773529912,
  1294757372,
  1396182291,
  1695183700,
  1986661051,
  2177026350,
  2456956037,
  2730485921,
  2820302411,
  3259730800,
  3345764771,
  3516065817,
  3600352804,
  4094571909,
  275423344,
  430227734,
  506948616,
  659060556,
  883997877,
  958139571,
  1322822218,
  1537002063,
  1747873779,
  1955562222,
  2024104815,
  2227730452,
  2361852424,
  2428436474,
  2756734187,
  3204031479,
  3329325298
]);
var SHA256_W = /* @__PURE__ */ new Uint32Array(64);
var SHA2_32B = class extends HashMD {
  // We cannot use array here since array allows indexing by variable
  // which means optimizer/compiler cannot use registers.
  // Numeric initializers matter: starting the fields as `undefined` changes
  // V8's field representation and makes sha256 3x slower (measured).
  A = 0;
  B = 0;
  C = 0;
  D = 0;
  E = 0;
  F = 0;
  G = 0;
  H = 0;
  constructor(outputLen, IV) {
    super(64, outputLen, 8, false);
    this.A = IV[0] | 0;
    this.B = IV[1] | 0;
    this.C = IV[2] | 0;
    this.D = IV[3] | 0;
    this.E = IV[4] | 0;
    this.F = IV[5] | 0;
    this.G = IV[6] | 0;
    this.H = IV[7] | 0;
  }
  get() {
    const { A, B, C, D, E, F, G, H } = this;
    return [A, B, C, D, E, F, G, H];
  }
  // prettier-ignore
  set(A, B, C, D, E, F, G, H) {
    this.A = A | 0;
    this.B = B | 0;
    this.C = C | 0;
    this.D = D | 0;
    this.E = E | 0;
    this.F = F | 0;
    this.G = G | 0;
    this.H = H | 0;
  }
  _cloneInto(to) {
    (to ||= new this.constructor()).set(...this.get());
    return this._cloneIntoMeta(to);
  }
  process(view, offset) {
    for (let i = 0; i < 16; i++, offset += 4)
      SHA256_W[i] = view.getUint32(offset, false);
    for (let i = 16; i < 64; i++) {
      const W15 = SHA256_W[i - 15];
      const W2 = SHA256_W[i - 2];
      const s0 = rotr(W15, 7) ^ rotr(W15, 18) ^ W15 >>> 3;
      const s1 = rotr(W2, 17) ^ rotr(W2, 19) ^ W2 >>> 10;
      SHA256_W[i] = s1 + SHA256_W[i - 7] + s0 + SHA256_W[i - 16] | 0;
    }
    let { A, B, C, D, E, F, G, H } = this;
    for (let i = 0; i < 64; i++) {
      const sigma1 = rotr(E, 6) ^ rotr(E, 11) ^ rotr(E, 25);
      const T1 = H + sigma1 + Chi(E, F, G) + SHA256_K[i] + SHA256_W[i] | 0;
      const sigma0 = rotr(A, 2) ^ rotr(A, 13) ^ rotr(A, 22);
      const T2 = sigma0 + Maj(A, B, C) | 0;
      H = G;
      G = F;
      F = E;
      E = D + T1 | 0;
      D = C;
      C = B;
      B = A;
      A = T1 + T2 | 0;
    }
    A = A + this.A | 0;
    B = B + this.B | 0;
    C = C + this.C | 0;
    D = D + this.D | 0;
    E = E + this.E | 0;
    F = F + this.F | 0;
    G = G + this.G | 0;
    H = H + this.H | 0;
    this.set(A, B, C, D, E, F, G, H);
  }
  roundClean() {
    clean(SHA256_W);
  }
  destroy() {
    this.destroyed = true;
    this.set(0, 0, 0, 0, 0, 0, 0, 0);
    clean(this.buffer);
  }
};
var _SHA256 = class extends SHA2_32B {
  constructor() {
    super(32, SHA256_IV);
  }
};
var sha256 = /* @__PURE__ */ createHasher(
  () => new _SHA256(),
  /* @__PURE__ */ oidNist(1)
);

// scripts/xdr-portable/crypto.mjs
function createHash(algorithm) {
  if (algorithm !== "sha256") throw new Error("UNSUPPORTED_HASH");
  const hash = sha256.create();
  return {
    update(value) {
      hash.update(utf8(value));
      return this;
    },
    digest(encoding) {
      if (encoding !== "hex") throw new Error("UNSUPPORTED_ENCODING");
      return bytesToHex(hash.digest());
    }
  };
}
function utf8(value) {
  const bytes = [];
  for (const character of value) {
    let point = character.codePointAt(0);
    if (point >= 55296 && point <= 57343) point = 65533;
    if (point < 128) bytes.push(point);
    else if (point < 2048) bytes.push(192 | point >> 6, 128 | point & 63);
    else if (point < 65536) bytes.push(224 | point >> 12, 128 | point >> 6 & 63, 128 | point & 63);
    else bytes.push(240 | point >> 18, 128 | point >> 12 & 63, 128 | point >> 6 & 63, 128 | point & 63);
  }
  return Uint8Array.from(bytes);
}

// xdr/brute-force/normalize-alert.mjs
function safeDescription(value) {
  return String(value ?? "").slice(0, 2e3).replace(/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?(?:-----END [A-Z ]*PRIVATE KEY-----|$)/gu, "[redacted]").replace(/\b(?:sb_secret_|sb_publishable_)[A-Za-z0-9_-]+|\bBearer\s+\S+|\beyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/giu, "[redacted]").replace(/["']?(?:password|passwd|token|secret|api[_-]?key|authorization|cookie|비밀번호|암호)["']?\s*[:=]\s*(?:"[^"]*"|'[^']*'|[^\s,;}]+)/giu, "[redacted]").replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/giu, "[redacted]").replace(/[\r\n\u0000-\u001f]/gu, " ");
}
function normalizeAlert(alert) {
  const rawTime = alert?.timestamp;
  const timestamp = typeof rawTime === "string" && Number.isFinite(Date.parse(rawTime)) ? new Date(rawTime).toISOString() : null;
  const raw = alert?.data !== void 0 || alert?.rule !== void 0;
  const source = raw ? alert?.data?.srcip : alert?.sourceAddress;
  const account = raw ? alert?.data?.srcuser : alert?.account;
  const level = raw ? alert?.rule?.level : alert?.level;
  const description = raw ? alert?.rule?.description : alert?.description;
  return {
    timestamp,
    sourceAddress: typeof source === "string" && isIP(source) ? source : null,
    account: typeof account !== "string" || !account || account.length > 256 || account === "[redacted]" ? "[redacted]" : /^user\d{1,8}$/u.test(account) || !raw && /^opaque:[a-f0-9]{16}$/u.test(account) ? account : "opaque:" + createHash("sha256").update(account).digest("hex").slice(0, 16),
    level: Number.isInteger(level) && level >= 0 && level <= 16 ? level : 0,
    description: safeDescription(description)
  };
}

// xdr/web-injection/jev.mjs
function createJevClient({
  enabled = typeof process !== "undefined" && process.env?.XDR_JEV_LIVE === "1",
  getApiKey = () => typeof process !== "undefined" ? process.env?.TYPESAFE_API_KEY : void 0,
  fetchImpl = globalThis.fetch,
  onStatus = () => {
  }
} = {}) {
  return async function askJev(summary, { signal } = {}) {
    if (!enabled) {
      onStatus("disabled");
      return null;
    }
    const key = getApiKey();
    if (typeof key !== "string" || !key.trim()) {
      onStatus("missing_key");
      return null;
    }
    const state = {
      level: Number.isInteger(summary.level) ? summary.level : 0,
      repeatCount: Number.isFinite(summary.repeatCount) ? summary.repeatCount : 0,
      sql: summary.sql === true,
      script: summary.script === true,
      traversal: summary.traversal === true,
      command: summary.command === true
    };
    try {
      const response = await fetchImpl("https://api.typesafe.ai/v1/systemone", {
        method: "POST",
        redirect: "error",
        signal,
        headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
        body: JSON.stringify({ model: "jev-latest", state, questions: {
          is_web_injection: {
            type: "noul",
            instructions: "Does this numerical evidence show repeated exploitation attempts against a public web application under MITRE ATT&CK T1190? A lone quote, topic word or missing evidence is uncertainty, not proof.",
            criteria: {
              true: "Repeated concrete SQL, script, path traversal or shell syntax attempts from the same source.",
              false: "Ordinary requests, isolated ambiguous fragments or classroom topic words without repeated attack syntax."
            }
          }
        } })
      });
      if (!response.ok) {
        onStatus(`http_${response.status}`);
        return null;
      }
      const answer = (await response.json())?.answers?.is_web_injection;
      const valid = answer?.type === "noul" && typeof answer.noul === "number" && Number.isFinite(answer.noul) && answer.noul >= 0 && answer.noul <= 1;
      onStatus(valid ? "answered" : "invalid_response");
      return valid ? answer.noul : null;
    } catch {
      onStatus("request_failed");
      return null;
    }
  };
}

// xdr/web-injection/signals.mjs
function inputSignals(value) {
  let text = typeof value === "string" ? value.slice(0, 12e3) : "";
  for (let i = 0; i < 2; i++) {
    try {
      const decoded = decodeURIComponent(text);
      if (decoded === text) break;
      text = decoded;
    } catch {
      break;
    }
  }
  return {
    sql: /\bunion\s+(?:all\s+)?select\b|['"]\s*(?:or|and)\s+(?:\d+\s*=\s*\d+|['"][^'"]*['"]\s*=)|;\s*(?:drop|select|insert|update|delete)\b|\b(?:sleep|pg_sleep)\s*\(/iu.test(text),
    script: /<\s*script\b|<[^>]{0,200}\bon(?:error|load|click)\s*=|javascript\s*:/iu.test(text),
    traversal: /(?:\.\.[/\\]){2,}/u.test(text),
    command: /(?:;|&&|\|\||`|\$\()\s*(?:cat|whoami|curl|wget|sh|bash|id)\b/iu.test(text)
  };
}
function patternName(signals) {
  return signals.sql ? "sql_injection" : signals.script ? "script_injection" : signals.traversal ? "path_traversal" : signals.command ? "command_injection" : null;
}

// xdr/web-injection/analyze.mjs
var output = (confidence, reason) => ({ action: confidence >= 0.85 ? "block" : confidence >= 0.5 ? "alert" : "record", confidence, reason });
function createDecider({ askJev = createJevClient(), timeoutMs = 1500 } = {}) {
  const windows = /* @__PURE__ */ new Map();
  return async function decide2(alert) {
    const row = normalizeAlert(alert), text = row.description;
    if (!row.timestamp || !row.sourceAddress) return output(0.5, "ambiguous_web_input: \uC785\uB825 \uADFC\uAC70 \uBD80\uC871");
    const syntax = inputSignals(text);
    const negated = /삽입 표식은 아닙|공격 표기는 없/u.test(text);
    const signals = {
      sql: !negated && (syntax.sql || /SQL (?:구문|표식)|데이터베이스 조회를 이어/u.test(text)),
      script: !negated && (syntax.script || /스크립트 (?:삽입|표식)|스크립트 표식/u.test(text)),
      traversal: syntax.traversal || /경로.{0,20}(?:거슬러|이탈)/u.test(text),
      command: syntax.command || /명령 구분자/u.test(text)
    };
    const pattern = patternName(signals);
    let count = Number(text.match(/(\d+)\s*(?:번|건|회)/u)?.[1] ?? (pattern ? 1 : 0));
    if (row.level <= 3 && !pattern) return output(0.05, "normal_activity: \uC8FC\uC785 \uADFC\uAC70 \uC5C6\uB294 \uC815\uC0C1 \uC870\uD68C");
    if (pattern && count < patterns_default.minRepeats) {
      const at = Date.parse(row.timestamp), previous = windows.get(row.sourceAddress) ?? [];
      const latest = Math.max(at, ...previous.map((item) => item.at));
      const active = previous.filter((item) => item.at > latest - patterns_default.windowSeconds * 1e3);
      const id = createHash("sha256").update(String(alert?.id ?? "") + row.timestamp + text).digest("hex");
      if (at > latest - patterns_default.windowSeconds * 1e3 && !active.some((item) => item.id === id)) active.push({ id, at, count: Math.max(1, count) });
      windows.delete(row.sourceAddress);
      windows.set(row.sourceAddress, active.slice(-128));
      if (windows.size > 512) windows.delete(windows.keys().next().value);
      count = active.reduce((sum, item) => sum + item.count, 0);
    }
    const repeated = Boolean(pattern && count >= patterns_default.minRepeats);
    if (repeated && (row.level >= 10 || windows.has(row.sourceAddress))) return output(0.96, pattern + ": \uAC19\uC740 \uC8FC\uC18C\uC758 \uBA85\uD655\uD55C \uBC18\uBCF5 \uC8FC\uC785");
    let timer;
    const controller = typeof AbortController === "function" ? new AbortController() : null;
    try {
      const response = Promise.resolve().then(() => askJev({ level: row.level, repeatCount: count, ...signals }, { signal: controller?.signal }));
      const score = typeof setTimeout === "function" ? await Promise.race([
        response,
        new Promise((resolve) => {
          timer = setTimeout(() => {
            controller?.abort();
            resolve(null);
          }, timeoutMs);
        })
      ]) : await response;
      if (typeof score !== "number" || !Number.isFinite(score) || score < 0 || score > 1) return output(0.5, "ambiguous_web_input: Jev \uC751\uB2F5 \uC5C6\uC74C \uB610\uB294 \uD615\uC2DD \uC624\uB958");
      return output(repeated ? score : Math.min(score, 0.84), "ambiguous_web_input: Jev \uD310\uB2E8");
    } catch {
      return output(0.5, "ambiguous_web_input: Jev \uC751\uB2F5 \uC5C6\uC74C");
    } finally {
      if (timer !== void 0 && typeof clearTimeout === "function") clearTimeout(timer);
    }
  };
}
var decide = createDecider();
export {
  createDecider,
  decide
};
