import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
await build({
  absWorkingDir: root,
  entryPoints: ['xdr/brute-force/analyze.mjs'],
  outfile: 'xdr/brute-force/decide.mjs',
  bundle: true, format: 'esm', platform: 'neutral', target: 'es2022',
  alias: { 'node:crypto': resolve(root, 'scripts/xdr-portable/crypto.mjs'),
    'node:net': resolve(root, 'scripts/xdr-portable/net.mjs') },
  banner: { js: '// Generated by npm run xdr:build from analyze.mjs; commit this standalone evaluator.\n// No runtime imports, disk access, or build-time secret substitution.' },
  legalComments: 'eof',
});
