import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
for (const moduleKey of ['brute-force', 'web-injection']) await build({
  absWorkingDir: root,
  entryPoints: [`xdr/${moduleKey}/analyze.mjs`],
  outfile: `xdr/${moduleKey}/decide.mjs`,
  bundle: true, format: 'esm', platform: 'neutral', target: 'es2022',
  alias: { 'node:crypto': resolve(root, 'scripts/xdr-portable/crypto.mjs'),
    'node:net': resolve(root, 'scripts/xdr-portable/net.mjs') },
  banner: { js: '// Generated by npm run xdr:build from analyze.mjs; commit this standalone evaluator.\n// No runtime imports, disk access, or build-time secret substitution.' },
  legalComments: 'eof',
});
